# generated by wxGlade 0.6.3

import wx

# begin wxGlade: extracode
from wx import GetTranslation as _
from widgets import VirtualListCtrl
# end wxGlade


class Main(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Main.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.split_main = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.panel_gliders = wx.Panel(self.split_main, -1)
        
        # Menu Bar
        self.main_menu = wx.MenuBar()
        self.menu_file = wx.Menu()
        self.menu_exit = wx.MenuItem(self.menu_file, wx.NewId(), _("E&xit\tAlt-F4"), _("Exit application"), wx.ITEM_NORMAL)
        self.menu_file.AppendItem(self.menu_exit)
        self.main_menu.Append(self.menu_file, _("&File"))
        self.menu_edit = wx.Menu()
        self.menu_coefficients = wx.MenuItem(self.menu_edit, wx.NewId(), _("&IGC handicap list..."), _("Edit gliders and IGC handicap list"), wx.ITEM_NORMAL)
        self.menu_edit.AppendItem(self.menu_coefficients)
        self.menu_pilots = wx.MenuItem(self.menu_edit, wx.NewId(), _("&Pilots..."), _("Edit pilots list"), wx.ITEM_NORMAL)
        self.menu_edit.AppendItem(self.menu_pilots)
        self.menu_organizations = wx.MenuItem(self.menu_edit, wx.NewId(), _("&Organizations or countries..."), _("Edit organizations or coutries list"), wx.ITEM_NORMAL)
        self.menu_edit.AppendItem(self.menu_organizations)
        self.main_menu.Append(self.menu_edit, _("&Edit"))
        self.menu_glider = wx.Menu()
        self.menu_glider_new = wx.MenuItem(self.menu_glider, wx.NewId(), _("&New...\tInsert"), _("Add new glider"), wx.ITEM_NORMAL)
        self.menu_glider.AppendItem(self.menu_glider_new)
        self.menu_glider_properties = wx.MenuItem(self.menu_glider, wx.NewId(), _("&Properties..."), _("Edit glider properties"), wx.ITEM_NORMAL)
        self.menu_glider.AppendItem(self.menu_glider_properties)
        self.menu_glider_delete = wx.MenuItem(self.menu_glider, wx.NewId(), _("&Delete"), _("Delete glider"), wx.ITEM_NORMAL)
        self.menu_glider.AppendItem(self.menu_glider_delete)
        self.main_menu.Append(self.menu_glider, _("&Gliders"))
        self.menu_help = wx.Menu()
        self.menu_about = wx.MenuItem(self.menu_help, wx.NewId(), _("&About\tF1"), _("About this application"), wx.ITEM_NORMAL)
        self.menu_help.AppendItem(self.menu_about)
        self.main_menu.Append(self.menu_help, _("&Help"))
        self.SetMenuBar(self.main_menu)
        # Menu Bar end
        self.statusbar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)
        self.text_find = wx.SearchCtrl(self.panel_gliders, -1)
        self.list_gliders = wx.ListCtrl(self.panel_gliders, -1, style=wx.LC_REPORT|wx.LC_VIRTUAL|wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER)
        self.button_glider_new = wx.Button(self.panel_gliders, wx.ID_NEW, "")
        self.button_glider_properties = wx.Button(self.panel_gliders, wx.ID_PROPERTIES, "")
        self.button_glider_delete = wx.Button(self.panel_gliders, wx.ID_DELETE, "")
        self.panel_card = wx.Panel(self.split_main, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Main.__set_properties
        self.SetTitle(_("IGC Weight"))
        self.statusbar.SetStatusWidths([-1])
        # statusbar fields
        statusbar_fields = [""]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.button_glider_new.SetToolTipString(_("Add new glider"))
        self.button_glider_properties.SetToolTipString(_("Edit glider properties"))
        self.button_glider_delete.SetToolTipString(_("Delete glider"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Main.__do_layout
        sizer_main = wx.BoxSizer(wx.HORIZONTAL)
        sizer_gliders = wx.BoxSizer(wx.VERTICAL)
        sizer_gliders_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_gliders.Add(self.text_find, 0, wx.LEFT|wx.TOP|wx.EXPAND, 4)
        sizer_gliders.Add(self.list_gliders, 1, wx.LEFT|wx.TOP|wx.BOTTOM|wx.EXPAND, 4)
        sizer_gliders_buttons.Add(self.button_glider_new, 1, wx.RIGHT, 2)
        sizer_gliders_buttons.Add(self.button_glider_properties, 1, wx.LEFT|wx.RIGHT, 2)
        sizer_gliders_buttons.Add(self.button_glider_delete, 1, wx.LEFT, 2)
        sizer_gliders.Add(sizer_gliders_buttons, 0, wx.LEFT|wx.BOTTOM|wx.EXPAND, 4)
        self.panel_gliders.SetSizer(sizer_gliders)
        self.split_main.SplitVertically(self.panel_gliders, self.panel_card, 350)
        sizer_main.Add(self.split_main, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Main


class DialogModel(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DialogModel.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.list_ctrl = VirtualListCtrl(self, -1)
        self.button_new = wx.Button(self, wx.ID_NEW, "")
        self.button_properties = wx.Button(self, wx.ID_PROPERTIES, "")
        self.button_delete = wx.Button(self, wx.ID_DELETE, "")
        self.panel_space = wx.Panel(self, -1)
        self.button_close = wx.Button(self, wx.ID_CLOSE, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: DialogModel.__set_properties
        self.SetTitle(_("Model"))
        self.list_ctrl.SetFocus()
        self.button_new.Enable(False)
        self.button_properties.Enable(False)
        self.button_delete.Enable(False)
        self.panel_space.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DialogModel.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        sizer_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_button_close = wx.BoxSizer(wx.HORIZONTAL)
        sizer_db_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_main.Add(self.list_ctrl, 1, wx.ALL|wx.EXPAND, 4)
        sizer_db_buttons.Add(self.button_new, 1, wx.RIGHT, 2)
        sizer_db_buttons.Add(self.button_properties, 1, wx.LEFT|wx.RIGHT, 2)
        sizer_db_buttons.Add(self.button_delete, 1, wx.LEFT, 2)
        sizer_buttons.Add(sizer_db_buttons, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 4)
        sizer_button_close.Add(self.panel_space, 1, wx.EXPAND, 0)
        sizer_button_close.Add(self.button_close, 0, 0, 0)
        sizer_buttons.Add(sizer_button_close, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 4)
        sizer_main.Add(sizer_buttons, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        self.Layout()
        # end wxGlade

# end of class DialogModel


class IgcHandicapForm(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: IgcHandicapForm.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_name = wx.StaticText(self, -1, _("Name"))
        self.label_coefficient = wx.StaticText(self, -1, _("Coefficient"))
        self.text_name = wx.TextCtrl(self, -1, "")
        self.text_coefficient = wx.TextCtrl(self, -1, "")
        self.label_weight_non_lifting = wx.StaticText(self, -1, _("Weight non-lifting"))
        self.label_mtow_without_water = wx.StaticText(self, -1, _("MTOW without water"))
        self.label_mtow = wx.StaticText(self, -1, _("MTOW"))
        self.label_weight_referential = wx.StaticText(self, -1, _("Weight referential"))
        self.text_weight_non_lifting = wx.TextCtrl(self, -1, "")
        self.text_mtow_without_water = wx.TextCtrl(self, -1, "")
        self.text_mtow = wx.TextCtrl(self, -1, "")
        self.text_weight_referential = wx.TextCtrl(self, -1, "")
        self.label_description = wx.StaticText(self, -1, _("Description"))
        self.text_description = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_WORDWRAP)
        self.button_ok = wx.Button(self, wx.ID_OK, "")
        self.button_cancel = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: IgcHandicapForm.__set_properties
        self.SetTitle(_("Glider type"))
        self.label_name.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_coefficient.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_name.SetFocus()
        self.button_ok.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: IgcHandicapForm.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        sizer_buttons = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer = wx.FlexGridSizer(6, 4, 2, 2)
        grid_sizer.Add(self.label_name, 0, wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_coefficient, 0, wx.LEFT|wx.EXPAND, 2)
        grid_sizer.Add(self.text_name, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_coefficient, 0, wx.LEFT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.label_weight_non_lifting, 0, wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_mtow_without_water, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_mtow, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_weight_referential, 0, wx.LEFT|wx.EXPAND, 2)
        grid_sizer.Add(self.text_weight_non_lifting, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_mtow_without_water, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_mtow, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_weight_referential, 0, wx.LEFT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.label_description, 0, wx.EXPAND, 0)
        grid_sizer.Add(self.text_description, 0, wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.AddGrowableRow(5)
        grid_sizer.AddGrowableCol(0)
        grid_sizer.AddGrowableCol(1)
        grid_sizer.AddGrowableCol(2)
        grid_sizer.AddGrowableCol(3)
        sizer_main.Add(grid_sizer, 1, wx.ALL|wx.EXPAND, 4)
        sizer_buttons.Add(self.button_ok, 0, wx.RIGHT, 2)
        sizer_buttons.Add(self.button_cancel, 0, wx.LEFT, 2)
        sizer_main.Add(sizer_buttons, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ALIGN_RIGHT, 4)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        self.Layout()
        # end wxGlade

# end of class IgcHandicapForm
