# generated by wxGlade 0.6.3

import wx

# begin wxGlade: extracode
from wx import GetTranslation as _
from gui_widgets import VirtualListCtrl
# end wxGlade


class GliderCardForm(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GliderCardForm.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizer_photo_staticbox = wx.StaticBox(self, -1, _("Photo"))
        self.label_registration = wx.StaticText(self, -1, _("Registration"))
        self.label_competition_number = wx.StaticText(self, -1, _("Competition number"))
        self.text_ctrl_registration = wx.TextCtrl(self, -1, "")
        self.text_ctrl_competition_number = wx.TextCtrl(self, -1, "")
        self.label_glider_type = wx.StaticText(self, -1, _("Glider type"))
        self.combo_box_glider_type = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.button_add_glide_type = wx.Button(self, -1, _("Add..."), style=wx.BU_EXACTFIT)
        self.label_pilot = wx.StaticText(self, -1, _("Pilot"))
        self.combo_box_pilot = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.button_pilot = wx.Button(self, -1, _("Add..."), style=wx.BU_EXACTFIT)
        self.label_organization = wx.StaticText(self, -1, _("Organization or country"))
        self.combo_box_organization = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.button_organization = wx.Button(self, -1, _("Add..."), style=wx.BU_EXACTFIT)
        self.checkbox_winglets = wx.CheckBox(self, -1, _("Winglets"))
        self.checkbox_gear = wx.CheckBox(self, -1, _("Landing gear"))
        self.photo = wx.StaticBitmap(self, -1)
        self.button_open_photo = wx.Button(self, wx.ID_OPEN, "")
        self.button_clear_photo = wx.Button(self, wx.ID_CLEAR, "")
        self.label_description = wx.StaticText(self, -1, _("Description"))
        self.text_description = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_WORDWRAP)
        self.button_ok = wx.Button(self, wx.ID_OK, "")
        self.button_cancel = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GliderCardForm.__set_properties
        self.SetTitle(_("Glider card"))
        self.text_ctrl_registration.SetFocus()
        self.button_add_glide_type.SetToolTipString(_("Add glider type"))
        self.button_pilot.SetToolTipString(_("Add pilot"))
        self.button_organization.SetToolTipString(_("Add organization or country"))
        self.button_open_photo.SetToolTipString(_("Open picture from file"))
        self.button_clear_photo.SetToolTipString(_("Clear picture"))
        self.button_ok.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GliderCardForm.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        sizer_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_description = wx.BoxSizer(wx.VERTICAL)
        sizer_glider_card = wx.BoxSizer(wx.HORIZONTAL)
        sizer_photo = wx.StaticBoxSizer(self.sizer_photo_staticbox, wx.VERTICAL)
        sizer_photo_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_data = wx.FlexGridSizer(9, 3, 2, 2)
        sizer_data.Add(self.label_registration, 0, wx.RIGHT|wx.EXPAND, 2)
        sizer_data.Add(self.label_competition_number, 0, wx.LEFT|wx.EXPAND, 2)
        sizer_data.Add(self.text_ctrl_registration, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        sizer_data.Add(self.text_ctrl_competition_number, 0, wx.LEFT|wx.BOTTOM|wx.EXPAND, 2)
        sizer_data.Add(self.label_glider_type, 0, wx.RIGHT|wx.EXPAND, 2)
        sizer_data.Add(self.combo_box_glider_type, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        sizer_data.Add(self.button_add_glide_type, 0, wx.LEFT|wx.BOTTOM, 2)
        sizer_data.Add(self.label_pilot, 0, wx.RIGHT|wx.EXPAND, 2)
        sizer_data.Add(self.combo_box_pilot, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        sizer_data.Add(self.button_pilot, 0, wx.LEFT|wx.BOTTOM, 2)
        sizer_data.Add(self.label_organization, 0, wx.RIGHT|wx.EXPAND, 2)
        sizer_data.Add(self.combo_box_organization, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        sizer_data.Add(self.button_organization, 0, wx.LEFT|wx.BOTTOM, 2)
        sizer_data.Add(self.checkbox_winglets, 0, wx.RIGHT|wx.EXPAND, 2)
        sizer_data.Add(self.checkbox_gear, 0, wx.LEFT|wx.EXPAND, 2)
        sizer_glider_card.Add(sizer_data, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 4)
        sizer_photo.Add(self.photo, 1, wx.EXPAND, 0)
        sizer_photo_buttons.Add(self.button_open_photo, 1, wx.RIGHT|wx.EXPAND, 2)
        sizer_photo_buttons.Add(self.button_clear_photo, 1, wx.LEFT|wx.EXPAND, 2)
        sizer_photo.Add(sizer_photo_buttons, 0, wx.ALL|wx.EXPAND, 4)
        sizer_glider_card.Add(sizer_photo, 0, wx.EXPAND, 0)
        sizer_main.Add(sizer_glider_card, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 4)
        sizer_description.Add(self.label_description, 0, wx.BOTTOM|wx.EXPAND, 2)
        sizer_description.Add(self.text_description, 1, wx.BOTTOM|wx.EXPAND, 2)
        sizer_main.Add(sizer_description, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 4)
        sizer_buttons.Add(self.button_ok, 0, wx.RIGHT, 2)
        sizer_buttons.Add(self.button_cancel, 0, wx.LEFT, 2)
        sizer_main.Add(sizer_buttons, 0, wx.ALL|wx.ALIGN_RIGHT, 4)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        self.Layout()
        # end wxGlade

# end of class GliderCardForm


class PilotForm(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PilotForm.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_degree = wx.StaticText(self, -1, _("Degree"))
        self.label_firstname = wx.StaticText(self, -1, _("Name"))
        self.label_surname = wx.StaticText(self, -1, _("Surname"))
        self.text_degree = wx.TextCtrl(self, -1, "")
        self.text_name = wx.TextCtrl(self, -1, "")
        self.text_surname = wx.TextCtrl(self, -1, "")
        self.label_year_of_birth = wx.StaticText(self, -1, _("Year of birth"))
        self.label_sex = wx.StaticText(self, -1, _("Sex"))
        self.text_year_of_birth = wx.TextCtrl(self, -1, "")
        self.text_sex = wx.TextCtrl(self, -1, "")
        self.label_description = wx.StaticText(self, -1, _("Description"))
        self.text_description = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_WORDWRAP)
        self.button_ok = wx.Button(self, wx.ID_OK, "")
        self.button_cancel = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PilotForm.__set_properties
        self.SetTitle(_("Pilot"))
        self.label_firstname.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_surname.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_ok.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PilotForm.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        sizer_buttons = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer = wx.FlexGridSizer(6, 8, 2, 2)
        grid_sizer.Add(self.label_degree, 0, wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_firstname, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_surname, 0, wx.LEFT|wx.EXPAND, 2)
        grid_sizer.Add(self.text_degree, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_name, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_surname, 0, wx.LEFT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.label_year_of_birth, 0, wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_sex, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.text_year_of_birth, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_sex, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.label_description, 0, wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.text_description, 0, wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.AddGrowableRow(5)
        grid_sizer.AddGrowableCol(0)
        grid_sizer.AddGrowableCol(1)
        grid_sizer.AddGrowableCol(2)
        grid_sizer.AddGrowableCol(3)
        grid_sizer.AddGrowableCol(4)
        grid_sizer.AddGrowableCol(5)
        grid_sizer.AddGrowableCol(6)
        grid_sizer.AddGrowableCol(7)
        sizer_main.Add(grid_sizer, 1, wx.ALL|wx.EXPAND, 4)
        sizer_buttons.Add(self.button_ok, 0, wx.RIGHT, 2)
        sizer_buttons.Add(self.button_cancel, 0, wx.LEFT, 2)
        sizer_main.Add(sizer_buttons, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ALIGN_RIGHT, 4)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        self.Layout()
        # end wxGlade

# end of class PilotForm


class Main(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Main.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.split_main = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.panel_card = wx.Panel(self.split_main, -1)
        self.sizer_photo_staticbox = wx.StaticBox(self.panel_card, -1, _("Photo"))
        self.panel_gliders = wx.Panel(self.split_main, -1)
        
        # Menu Bar
        self.main_menu = wx.MenuBar()
        self.menu_file = wx.Menu()
        self.menu_exit = wx.MenuItem(self.menu_file, wx.NewId(), _("E&xit\tAlt-F4"), _("Exit application"), wx.ITEM_NORMAL)
        self.menu_file.AppendItem(self.menu_exit)
        self.main_menu.Append(self.menu_file, _("&File"))
        self.menu_edit = wx.Menu()
        self.menu_coefficients = wx.MenuItem(self.menu_edit, wx.NewId(), _("&IGC handicap list..."), _("Edit gliders and IGC handicap list"), wx.ITEM_NORMAL)
        self.menu_edit.AppendItem(self.menu_coefficients)
        self.menu_pilots = wx.MenuItem(self.menu_edit, wx.NewId(), _("&Pilots..."), _("Edit pilots list"), wx.ITEM_NORMAL)
        self.menu_edit.AppendItem(self.menu_pilots)
        self.menu_organizations = wx.MenuItem(self.menu_edit, wx.NewId(), _("&Organizations or countries..."), _("Edit organizations or coutries list"), wx.ITEM_NORMAL)
        self.menu_edit.AppendItem(self.menu_organizations)
        self.main_menu.Append(self.menu_edit, _("&Edit"))
        self.menu_glider_card = wx.Menu()
        self.menu_glider_card_new = wx.MenuItem(self.menu_glider_card, wx.NewId(), _("&New...\tInsert"), _("Add new glider"), wx.ITEM_NORMAL)
        self.menu_glider_card.AppendItem(self.menu_glider_card_new)
        self.menu_glider_card_properties = wx.MenuItem(self.menu_glider_card, wx.NewId(), _("&Properties..."), _("Edit glider properties"), wx.ITEM_NORMAL)
        self.menu_glider_card.AppendItem(self.menu_glider_card_properties)
        self.menu_glider_card_delete = wx.MenuItem(self.menu_glider_card, wx.NewId(), _("&Delete"), _("Delete glider"), wx.ITEM_NORMAL)
        self.menu_glider_card.AppendItem(self.menu_glider_card_delete)
        self.main_menu.Append(self.menu_glider_card, _("&Glider card"))
        self.menu_help = wx.Menu()
        self.menu_about = wx.MenuItem(self.menu_help, wx.NewId(), _("&About\tF1"), _("About this application"), wx.ITEM_NORMAL)
        self.menu_help.AppendItem(self.menu_about)
        self.main_menu.Append(self.menu_help, _("&Help"))
        self.SetMenuBar(self.main_menu)
        # Menu Bar end
        self.statusbar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)
        self.text_find = wx.SearchCtrl(self.panel_gliders, -1, style=wx.TE_PROCESS_ENTER)
        self.list_glider_card = VirtualListCtrl(self.panel_gliders, -1)
        self.button_glider_card_new = wx.Button(self.panel_gliders, wx.ID_NEW, "")
        self.button_glider_card_properties = wx.Button(self.panel_gliders, wx.ID_PROPERTIES, "")
        self.button_glider_card_delete = wx.Button(self.panel_gliders, wx.ID_DELETE, "")
        self.label_registration = wx.StaticText(self.panel_card, -1, _("Registration"))
        self.label_competition_number = wx.StaticText(self.panel_card, -1, _("Competition number"))
        self.text_registration = wx.StaticText(self.panel_card, -1, "")
        self.text_competition_number = wx.StaticText(self.panel_card, -1, "")
        self.label_glider_type = wx.StaticText(self.panel_card, -1, _("Glider type"))
        self.text_glider_type = wx.StaticText(self.panel_card, -1, "")
        self.label_pilot = wx.StaticText(self.panel_card, -1, _("Pilot"))
        self.text_pilot = wx.StaticText(self.panel_card, -1, "")
        self.label_organization = wx.StaticText(self.panel_card, -1, _("Organization or country"))
        self.text_organization = wx.StaticText(self.panel_card, -1, "")
        self.text_winglets = wx.StaticText(self.panel_card, -1, _("Winglets"))
        self.text_landing_gear = wx.StaticText(self.panel_card, -1, _("Landing gear"))
        self.label_description = wx.StaticText(self.panel_card, -1, _("Description"))
        self.text_description = wx.StaticText(self.panel_card, -1, "")
        self.photo = wx.StaticBitmap(self.panel_card, -1)
        self.button_show_photo = wx.Button(self.panel_card, wx.ID_ZOOM_IN, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Main.__set_properties
        self.SetTitle(_("IGC Weight"))
        self.statusbar.SetStatusWidths([-1])
        # statusbar fields
        statusbar_fields = [""]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.list_glider_card.SetFocus()
        self.button_glider_card_new.SetToolTipString(_("Add new glider"))
        self.button_glider_card_new.Enable(False)
        self.button_glider_card_properties.SetToolTipString(_("Edit glider properties"))
        self.button_glider_card_properties.Enable(False)
        self.button_glider_card_delete.SetToolTipString(_("Delete glider"))
        self.button_glider_card_delete.Enable(False)
        self.text_registration.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.text_registration.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_competition_number.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.text_competition_number.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_glider_type.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.text_glider_type.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_pilot.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.text_pilot.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_organization.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.text_organization.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_winglets.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_landing_gear.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_description.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.photo.SetMinSize((180, -1))
        self.button_show_photo.SetToolTipString(_("Show photo"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Main.__do_layout
        sizer_main = wx.BoxSizer(wx.HORIZONTAL)
        sizer_card = wx.BoxSizer(wx.VERTICAL)
        sizer_card_head = wx.BoxSizer(wx.HORIZONTAL)
        sizer_photo = wx.StaticBoxSizer(self.sizer_photo_staticbox, wx.VERTICAL)
        sizer_card_base = wx.FlexGridSizer(11, 2, 0, 0)
        sizer_gliders = wx.BoxSizer(wx.VERTICAL)
        sizer_gliders_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_gliders.Add(self.text_find, 0, wx.LEFT|wx.TOP|wx.EXPAND, 4)
        sizer_gliders.Add(self.list_glider_card, 1, wx.LEFT|wx.TOP|wx.BOTTOM|wx.EXPAND, 4)
        sizer_gliders_buttons.Add(self.button_glider_card_new, 1, wx.RIGHT, 2)
        sizer_gliders_buttons.Add(self.button_glider_card_properties, 1, wx.LEFT|wx.RIGHT, 2)
        sizer_gliders_buttons.Add(self.button_glider_card_delete, 1, wx.LEFT, 2)
        sizer_gliders.Add(sizer_gliders_buttons, 0, wx.LEFT|wx.BOTTOM|wx.EXPAND, 4)
        self.panel_gliders.SetSizer(sizer_gliders)
        sizer_card_base.Add(self.label_registration, 1, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.label_competition_number, 1, wx.LEFT|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.text_registration, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.text_competition_number, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.label_glider_type, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.text_glider_type, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.label_pilot, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.text_pilot, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.label_organization, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.text_organization, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.text_winglets, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.text_landing_gear, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.EXPAND, 0)
        sizer_card_base.Add(self.label_description, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.Add(self.text_description, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 2)
        sizer_card_base.AddGrowableRow(10)
        sizer_card_base.AddGrowableCol(0)
        sizer_card_base.AddGrowableCol(1)
        sizer_card_head.Add(sizer_card_base, 1, wx.ALL|wx.EXPAND, 4)
        sizer_photo.Add(self.photo, 1, wx.ALL|wx.EXPAND, 4)
        sizer_photo.Add(self.button_show_photo, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 4)
        sizer_card_head.Add(sizer_photo, 0, wx.ALL|wx.EXPAND, 4)
        sizer_card.Add(sizer_card_head, 1, wx.EXPAND, 0)
        self.panel_card.SetSizer(sizer_card)
        self.split_main.SplitVertically(self.panel_gliders, self.panel_card)
        sizer_main.Add(self.split_main, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Main


class DialogModel(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DialogModel.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.list_ctrl = VirtualListCtrl(self, -1)
        self.button_new = wx.Button(self, wx.ID_NEW, "")
        self.button_properties = wx.Button(self, wx.ID_EDIT, "")
        self.button_delete = wx.Button(self, wx.ID_DELETE, "")
        self.panel_space = wx.Panel(self, -1)
        self.button_close = wx.Button(self, wx.ID_CLOSE, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: DialogModel.__set_properties
        self.SetTitle(_("Model"))
        self.list_ctrl.SetFocus()
        self.button_new.SetToolTipString(_("Add new item"))
        self.button_new.Enable(False)
        self.button_properties.SetToolTipString(_("Edit item"))
        self.button_properties.Enable(False)
        self.button_delete.SetToolTipString(_("Delete item"))
        self.button_delete.Enable(False)
        self.panel_space.Enable(False)
        self.button_close.SetToolTipString(_("Close window"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DialogModel.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        sizer_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_button_close = wx.BoxSizer(wx.HORIZONTAL)
        sizer_db_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_main.Add(self.list_ctrl, 1, wx.ALL|wx.EXPAND, 4)
        sizer_db_buttons.Add(self.button_new, 1, wx.RIGHT, 2)
        sizer_db_buttons.Add(self.button_properties, 1, wx.LEFT|wx.RIGHT, 2)
        sizer_db_buttons.Add(self.button_delete, 1, wx.LEFT, 2)
        sizer_buttons.Add(sizer_db_buttons, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 4)
        sizer_button_close.Add(self.panel_space, 1, wx.EXPAND, 0)
        sizer_button_close.Add(self.button_close, 0, 0, 0)
        sizer_buttons.Add(sizer_button_close, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 4)
        sizer_main.Add(sizer_buttons, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        self.Layout()
        # end wxGlade

# end of class DialogModel


class IgcHandicapForm(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: IgcHandicapForm.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_name = wx.StaticText(self, -1, _("Name"))
        self.label_coefficient = wx.StaticText(self, -1, _("Coefficient"))
        self.text_name = wx.TextCtrl(self, -1, "")
        self.text_coefficient = wx.TextCtrl(self, -1, "")
        self.label_weight_non_lifting = wx.StaticText(self, -1, _("Weight non-lifting"))
        self.label_mtow_without_water = wx.StaticText(self, -1, _("MTOW without water"))
        self.label_mtow = wx.StaticText(self, -1, _("MTOW"))
        self.label_weight_referential = wx.StaticText(self, -1, _("Weight referential"))
        self.text_weight_non_lifting = wx.TextCtrl(self, -1, "")
        self.text_mtow_without_water = wx.TextCtrl(self, -1, "")
        self.text_mtow = wx.TextCtrl(self, -1, "")
        self.text_weight_referential = wx.TextCtrl(self, -1, "")
        self.label_description = wx.StaticText(self, -1, _("Description"))
        self.text_description = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_WORDWRAP)
        self.button_ok = wx.Button(self, wx.ID_OK, "")
        self.button_cancel = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: IgcHandicapForm.__set_properties
        self.SetTitle(_("Glider type"))
        self.label_name.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_coefficient.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_name.SetFocus()
        self.button_ok.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: IgcHandicapForm.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        sizer_buttons = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer = wx.FlexGridSizer(6, 4, 2, 2)
        grid_sizer.Add(self.label_name, 0, wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_coefficient, 0, wx.LEFT|wx.EXPAND, 2)
        grid_sizer.Add(self.text_name, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_coefficient, 0, wx.LEFT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.label_weight_non_lifting, 0, wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_mtow_without_water, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_mtow, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 2)
        grid_sizer.Add(self.label_weight_referential, 0, wx.LEFT|wx.EXPAND, 2)
        grid_sizer.Add(self.text_weight_non_lifting, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_mtow_without_water, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_mtow, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.text_weight_referential, 0, wx.LEFT|wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.Add(self.label_description, 0, wx.EXPAND, 0)
        grid_sizer.Add(self.text_description, 0, wx.BOTTOM|wx.EXPAND, 2)
        grid_sizer.AddGrowableRow(5)
        grid_sizer.AddGrowableCol(0)
        grid_sizer.AddGrowableCol(1)
        grid_sizer.AddGrowableCol(2)
        grid_sizer.AddGrowableCol(3)
        sizer_main.Add(grid_sizer, 1, wx.ALL|wx.EXPAND, 4)
        sizer_buttons.Add(self.button_ok, 0, wx.RIGHT, 2)
        sizer_buttons.Add(self.button_cancel, 0, wx.LEFT, 2)
        sizer_main.Add(sizer_buttons, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ALIGN_RIGHT, 4)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        self.Layout()
        # end wxGlade

# end of class IgcHandicapForm
